# DISABLED: Using GitHub Actions for deployment instead
# This prevents cPanel from trying to build (which fails due to memory constraints)
# The GitHub Actions workflow will handle building and deploying

# cPanel Git deployment is disabled - no automatic deployment will occur
# GitHub Actions will build and deploy via FTP instead

# Note: If you want to re-enable cPanel deployment later,
# restore the original .cpanel.yml content from git history
