deployment:
  tasks:
    # Configure your application directory on the server
    - export DEPLOY_ROOT="$HOME/Almari2"

    # Ensure deploy root exists
    - /bin/mkdir -p "$DEPLOY_ROOT"

    # Sync repository files to the application directory (no build here)
    - /usr/bin/rsync -a --delete \
        --exclude ".git" \
        --exclude "node_modules" \
        --exclude ".next" \
        --exclude ".github" \
        --exclude "cpanel-deploy.sh" \
        --exclude "build-no-swc.sh" \
        ./ "$DEPLOY_ROOT"/

    # If a prebuilt .next exists in the repo (or was uploaded), sync it
    - if [ -d .next ]; then /usr/bin/rsync -a --delete .next/ "$DEPLOY_ROOT"/.next/; fi || true

    # Set safe permissions
    - /bin/chmod -R g+w "$DEPLOY_ROOT" || true

    # Touch Passenger restart file to restart the Node app managed by cPanel
    - /bin/mkdir -p "$DEPLOY_ROOT"/tmp && /usr/bin/touch "$DEPLOY_ROOT"/tmp/restart.txt